// Compact place gazetteer for tagging headlines. Country names, common aliases,
// demonyms, and roughly 250 travel cities and landmarks, mapped to ISO 3166-1
// alpha-2. Terms are pipe-separated and written the way a headline writes them;
// the tagger lowercases and strips accents when it builds the lookup.

export const COUNTRY_TERMS = {
  // Europe
  AD: 'Andorra|Andorran',
  AL: 'Albania|Albanian',
  AT: 'Austria|Austrian',
  AX: 'Aland Islands|Åland Islands',
  BA: 'Bosnia and Herzegovina|Bosnia|Bosnian|Herzegovina',
  BE: 'Belgium|Belgian',
  BG: 'Bulgaria|Bulgarian',
  BY: 'Belarus|Belarusian',
  CH: 'Switzerland|Swiss',
  CY: 'Cyprus|Cypriot',
  CZ: 'Czechia|Czech Republic|Czech',
  DE: 'Germany|German',
  DK: 'Denmark|Danish',
  EE: 'Estonia|Estonian',
  ES: 'Spain|Spanish|Spaniard',
  FI: 'Finland|Finnish',
  FO: 'Faroe Islands|Faroes|Faroese',
  FR: 'France|French',
  GB: 'United Kingdom|Great Britain|Britain|British|England|English|Scotland|Scottish|Wales|Welsh|Northern Ireland',
  GG: 'Guernsey',
  GI: 'Gibraltar',
  GR: 'Greece|Greek',
  HR: 'Croatia|Croatian',
  HU: 'Hungary|Hungarian',
  IE: 'Ireland|Irish',
  IM: 'Isle of Man',
  IS: 'Iceland|Icelandic',
  IT: 'Italy|Italian',
  JE: 'Jersey',
  LI: 'Liechtenstein',
  LT: 'Lithuania|Lithuanian',
  LU: 'Luxembourg',
  LV: 'Latvia|Latvian',
  MC: 'Monaco|Monegasque',
  MD: 'Moldova|Moldovan',
  ME: 'Montenegro|Montenegrin',
  MK: 'North Macedonia|Macedonia|Macedonian',
  MT: 'Malta|Maltese',
  NL: 'Netherlands|Holland|Dutch',
  NO: 'Norway|Norwegian',
  PL: 'Poland|Polish',
  PT: 'Portugal|Portuguese',
  RO: 'Romania|Romanian',
  RS: 'Serbia|Serbian',
  RU: 'Russia|Russian',
  SE: 'Sweden|Swedish',
  SI: 'Slovenia|Slovenian',
  SJ: 'Svalbard',
  SK: 'Slovakia|Slovak',
  SM: 'San Marino',
  TR: 'Turkiye|Türkiye|Turkey|Turkish',
  UA: 'Ukraine|Ukrainian',
  VA: 'Vatican City|Vatican|Holy See',
  XK: 'Kosovo|Kosovar',

  // Asia
  AF: 'Afghanistan|Afghan',
  AM: 'Armenia|Armenian',
  AZ: 'Azerbaijan|Azerbaijani',
  BD: 'Bangladesh|Bangladeshi',
  BN: 'Brunei',
  BT: 'Bhutan|Bhutanese',
  CN: 'China|Chinese',
  GE: 'Georgia|Georgian',
  HK: 'Hong Kong',
  ID: 'Indonesia|Indonesian',
  IN: 'India|Indian',
  IO: 'British Indian Ocean Territory|Diego Garcia',
  JP: 'Japan|Japanese',
  KG: 'Kyrgyzstan|Kyrgyz',
  KH: 'Cambodia|Cambodian',
  KP: 'North Korea|North Korean',
  KR: 'South Korea|South Korean|Korea|Korean',
  KZ: 'Kazakhstan|Kazakh',
  LA: 'Laos|Laotian',
  LK: 'Sri Lanka|Sri Lankan',
  MM: 'Myanmar|Burma|Burmese',
  MN: 'Mongolia|Mongolian',
  MO: 'Macau|Macao',
  MV: 'Maldives|Maldivian',
  MY: 'Malaysia|Malaysian',
  NP: 'Nepal|Nepalese|Nepali',
  PH: 'Philippines|Philippine|Filipino',
  PK: 'Pakistan|Pakistani',
  SG: 'Singapore|Singaporean',
  TH: 'Thailand|Thai',
  TJ: 'Tajikistan|Tajik',
  TL: 'Timor-Leste|East Timor',
  TM: 'Turkmenistan|Turkmen',
  TW: 'Taiwan|Taiwanese',
  UZ: 'Uzbekistan|Uzbek',
  VN: 'Vietnam|Viet Nam|Vietnamese',

  // Middle East
  AE: 'United Arab Emirates|Emirati',
  BH: 'Bahrain|Bahraini',
  IL: 'Israel|Israeli',
  IQ: 'Iraq|Iraqi',
  IR: 'Iran|Iranian',
  JO: 'Jordan|Jordanian',
  KW: 'Kuwait|Kuwaiti',
  LB: 'Lebanon|Lebanese',
  OM: 'Oman|Omani',
  PS: 'Palestine|Palestinian|Gaza|West Bank',
  QA: 'Qatar|Qatari',
  SA: 'Saudi Arabia|Saudi',
  SY: 'Syria|Syrian',
  YE: 'Yemen|Yemeni',

  // Africa
  AO: 'Angola|Angolan',
  BF: 'Burkina Faso',
  BI: 'Burundi',
  BJ: 'Benin',
  BW: 'Botswana',
  CD: 'Democratic Republic of the Congo|DR Congo|Congo-Kinshasa',
  CF: 'Central African Republic',
  CG: 'Republic of the Congo|Congo-Brazzaville|Congo',
  CI: 'Ivory Coast|Cote d\'Ivoire|Côte d\'Ivoire|Ivorian',
  CM: 'Cameroon|Cameroonian',
  CV: 'Cape Verde|Cabo Verde',
  DJ: 'Djibouti',
  DZ: 'Algeria|Algerian',
  EG: 'Egypt|Egyptian',
  EH: 'Western Sahara',
  ER: 'Eritrea|Eritrean',
  ET: 'Ethiopia|Ethiopian',
  GA: 'Gabon|Gabonese',
  GH: 'Ghana|Ghanaian',
  GM: 'Gambia|Gambian',
  GN: 'Guinea|Guinean',
  GQ: 'Equatorial Guinea',
  GW: 'Guinea-Bissau',
  KE: 'Kenya|Kenyan',
  KM: 'Comoros',
  LR: 'Liberia|Liberian',
  LS: 'Lesotho',
  LY: 'Libya|Libyan',
  MA: 'Morocco|Moroccan',
  MG: 'Madagascar|Malagasy',
  ML: 'Mali|Malian',
  MR: 'Mauritania|Mauritanian',
  MU: 'Mauritius|Mauritian',
  MW: 'Malawi|Malawian',
  MZ: 'Mozambique|Mozambican',
  NA: 'Namibia|Namibian',
  NE: 'Niger|Nigerien',
  NG: 'Nigeria|Nigerian',
  RE: 'Reunion|Réunion',
  RW: 'Rwanda|Rwandan',
  SC: 'Seychelles|Seychellois',
  SD: 'Sudan|Sudanese',
  SL: 'Sierra Leone',
  SN: 'Senegal|Senegalese',
  SO: 'Somalia|Somali',
  SS: 'South Sudan',
  ST: 'Sao Tome and Principe|São Tomé and Príncipe',
  SZ: 'Eswatini|Swaziland',
  TD: 'Chad|Chadian',
  TG: 'Togo|Togolese',
  TN: 'Tunisia|Tunisian',
  TZ: 'Tanzania|Tanzanian',
  UG: 'Uganda|Ugandan',
  YT: 'Mayotte',
  ZA: 'South Africa|South African',
  ZM: 'Zambia|Zambian',
  ZW: 'Zimbabwe|Zimbabwean',

  // Americas
  AG: 'Antigua and Barbuda|Barbuda',
  AI: 'Anguilla',
  AR: 'Argentina|Argentine|Argentinian',
  AW: 'Aruba',
  BB: 'Barbados|Barbadian',
  BL: 'Saint Barthelemy|St Barts|Saint Barts',
  BM: 'Bermuda|Bermudian',
  BO: 'Bolivia|Bolivian',
  BQ: 'Bonaire',
  BR: 'Brazil|Brazilian',
  BS: 'Bahamas|Bahamian',
  BZ: 'Belize|Belizean',
  CA: 'Canada|Canadian',
  CL: 'Chile|Chilean',
  CO: 'Colombia|Colombian',
  CR: 'Costa Rica|Costa Rican',
  CU: 'Cuba|Cuban',
  CW: 'Curacao|Curaçao',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  EC: 'Ecuador|Ecuadorian',
  FK: 'Falkland Islands|Falklands',
  GD: 'Grenada|Grenadian',
  GF: 'French Guiana',
  GL: 'Greenland|Greenlandic',
  GP: 'Guadeloupe',
  GT: 'Guatemala|Guatemalan',
  GY: 'Guyana|Guyanese',
  HN: 'Honduras|Honduran',
  HT: 'Haiti|Haitian',
  JM: 'Jamaica|Jamaican',
  KN: 'Saint Kitts and Nevis|St Kitts|Nevis',
  KY: 'Cayman Islands|Caymans',
  LC: 'Saint Lucia|St Lucia',
  MF: 'Saint Martin|St Martin',
  MQ: 'Martinique',
  MS: 'Montserrat',
  MX: 'Mexico|Mexican',
  NI: 'Nicaragua|Nicaraguan',
  PA: 'Panama|Panamanian',
  PE: 'Peru|Peruvian',
  PM: 'Saint Pierre and Miquelon',
  PR: 'Puerto Rico|Puerto Rican',
  PY: 'Paraguay|Paraguayan',
  SR: 'Suriname',
  SV: 'El Salvador|Salvadoran',
  SX: 'Sint Maarten',
  TC: 'Turks and Caicos|Turks and Caicos Islands',
  TT: 'Trinidad and Tobago|Trinidad|Tobago',
  US: 'United States|U.S.A.|U.S.|USA|America|American',
  UY: 'Uruguay|Uruguayan',
  VC: 'Saint Vincent and the Grenadines|St Vincent',
  VE: 'Venezuela|Venezuelan',
  VG: 'British Virgin Islands',
  VI: 'US Virgin Islands|U.S. Virgin Islands',

  // Oceania
  AS: 'American Samoa',
  AU: 'Australia|Australian',
  CC: 'Cocos Islands',
  CK: 'Cook Islands',
  CX: 'Christmas Island',
  FJ: 'Fiji|Fijian',
  FM: 'Micronesia',
  GU: 'Guam',
  KI: 'Kiribati',
  MH: 'Marshall Islands',
  MP: 'Northern Mariana Islands',
  NC: 'New Caledonia',
  NF: 'Norfolk Island',
  NR: 'Nauru',
  NU: 'Niue',
  NZ: 'New Zealand|New Zealander',
  PF: 'French Polynesia',
  PG: 'Papua New Guinea',
  PN: 'Pitcairn',
  PW: 'Palau',
  SB: 'Solomon Islands',
  TK: 'Tokelau',
  TO: 'Tonga|Tongan',
  TV: 'Tuvalu',
  VU: 'Vanuatu',
  WF: 'Wallis and Futuna',
  WS: 'Samoa|Samoan',
};

export const CITY_TERMS = {
  GB: 'London|Heathrow|Gatwick|Edinburgh|Glasgow|Manchester|Birmingham|Liverpool|Bristol|Belfast|Cornwall|Cotswolds',
  FR: 'Paris|Charles de Gaulle|Nice|Lyon|Marseille|Bordeaux|Toulouse|Cannes|Corsica|Normandy|Provence|Loire Valley|Chamonix',
  IT: 'Rome|Milan|Venice|Florence|Naples|Bologna|Turin|Verona|Palermo|Catania|Amalfi Coast|Amalfi|Tuscany|Sicily|Sardinia|Dolomites|Lake Como',
  ES: 'Madrid|Barcelona|Seville|Valencia|Malaga|Palma|Mallorca|Majorca|Ibiza|Menorca|Bilbao|Granada|Canary Islands|Tenerife|Lanzarote|Gran Canaria|Santiago de Compostela|Costa del Sol',
  PT: 'Lisbon|Porto|Madeira|Algarve|Azores|Sintra',
  NL: 'Amsterdam|Rotterdam|The Hague|Schiphol|Utrecht',
  BE: 'Brussels|Bruges|Antwerp|Ghent',
  DE: 'Berlin|Munich|Frankfurt|Hamburg|Cologne|Dusseldorf|Düsseldorf|Bavaria|Black Forest',
  AT: 'Vienna|Salzburg|Innsbruck|Tyrol',
  CH: 'Zurich|Geneva|Basel|Lucerne|Zermatt|Interlaken|St Moritz',
  CZ: 'Prague',
  HU: 'Budapest',
  PL: 'Warsaw|Krakow|Kraków|Gdansk|Gdańsk|Wroclaw',
  DK: 'Copenhagen|Aarhus',
  SE: 'Stockholm|Gothenburg|Malmo|Lapland',
  NO: 'Oslo|Bergen|Tromso|Tromsø|Lofoten|Norwegian fjords',
  FI: 'Helsinki|Rovaniemi',
  IS: 'Reykjavik|Reykjavík|Keflavik',
  IE: 'Dublin|Galway|Cork|Killarney|Ring of Kerry',
  GR: 'Athens|Santorini|Mykonos|Crete|Rhodes|Thessaloniki|Corfu|Naxos|Paros|Zakynthos',
  TR: 'Istanbul|Ankara|Antalya|Izmir|Cappadocia|Bodrum|Ephesus',
  HR: 'Dubrovnik|Split|Zagreb|Hvar|Istria',
  SI: 'Ljubljana|Lake Bled',
  RS: 'Belgrade',
  BG: 'Sofia|Plovdiv|Bansko|Sunny Beach',
  BA: 'Sarajevo|Mostar',
  RO: 'Bucharest|Transylvania|Brasov',
  UA: 'Kyiv|Kiev|Lviv|Odesa|Odessa',
  RU: 'Moscow|St Petersburg|Saint Petersburg',
  LV: 'Riga',
  LT: 'Vilnius',
  EE: 'Tallinn',
  MT: 'Valletta',
  AL: 'Tirana|Albanian Riviera',

  JP: 'Tokyo|Osaka|Kyoto|Sapporo|Fukuoka|Nagoya|Okinawa|Hokkaido|Haneda|Narita|Hiroshima|Mount Fuji',
  KR: 'Seoul|Busan|Jeju|Incheon',
  CN: 'Beijing|Shanghai|Guangzhou|Shenzhen|Chengdu|Xian|Hangzhou|Sanya|Great Wall',
  MO: 'Macau',
  TW: 'Taipei|Kaohsiung',
  TH: 'Bangkok|Phuket|Chiang Mai|Krabi|Koh Samui|Pattaya|Koh Phangan|Suvarnabhumi',
  VN: 'Hanoi|Ho Chi Minh City|Saigon|Da Nang|Hoi An|Ha Long Bay|Phu Quoc',
  KH: 'Phnom Penh|Siem Reap|Angkor Wat',
  LA: 'Vientiane|Luang Prabang',
  MM: 'Yangon|Bagan',
  MY: 'Kuala Lumpur|Penang|Langkawi|Kota Kinabalu|Malacca',
  ID: 'Jakarta|Bali|Ubud|Lombok|Yogyakarta|Komodo|Denpasar|Raja Ampat',
  PH: 'Manila|Cebu|Boracay|Palawan|El Nido|Siargao',
  IN: 'Delhi|New Delhi|Mumbai|Bengaluru|Bangalore|Chennai|Kolkata|Goa|Jaipur|Kerala|Hyderabad|Agra|Taj Mahal|Udaipur|Rajasthan|Ladakh|Varanasi',
  NP: 'Kathmandu|Pokhara|Everest Base Camp|Mount Everest',
  LK: 'Colombo|Kandy|Galle',
  MV: 'Male|Malé',
  BD: 'Dhaka',
  PK: 'Karachi|Lahore|Islamabad',
  KZ: 'Almaty|Astana',
  UZ: 'Tashkent|Samarkand|Bukhara',
  KG: 'Bishkek',
  MN: 'Ulaanbaatar',
  BT: 'Thimphu|Paro',
  GE: 'Tbilisi|Batumi',
  AM: 'Yerevan',
  AZ: 'Baku',

  AE: 'Dubai|Abu Dhabi|Sharjah|Ras Al Khaimah|DXB',
  QA: 'Doha|Hamad International',
  SA: 'Riyadh|Jeddah|Mecca|Medina|AlUla|Red Sea Project|Neom',
  OM: 'Muscat|Salalah',
  BH: 'Manama',
  KW: 'Kuwait City',
  JO: 'Amman|Petra|Wadi Rum|Dead Sea|Aqaba',
  LB: 'Beirut',
  IL: 'Tel Aviv|Jerusalem|Eilat',
  IR: 'Tehran|Isfahan|Shiraz',
  IQ: 'Baghdad|Erbil',
  SY: 'Damascus|Aleppo',
  YE: 'Sanaa|Socotra',

  EG: 'Cairo|Luxor|Sharm el Sheikh|Hurghada|Alexandria|Aswan|Giza|Pyramids of Giza',
  MA: 'Marrakech|Marrakesh|Casablanca|Fez|Tangier|Rabat|Agadir|Essaouira|Chefchaouen|Atlas Mountains',
  TN: 'Tunis|Djerba',
  DZ: 'Algiers',
  ZA: 'Cape Town|Johannesburg|Durban|Pretoria|Kruger National Park|Kruger|Garden Route|Table Mountain',
  KE: 'Nairobi|Mombasa|Masai Mara|Maasai Mara|Diani',
  TZ: 'Zanzibar|Dar es Salaam|Serengeti|Kilimanjaro|Arusha|Ngorongoro',
  UG: 'Kampala|Bwindi',
  RW: 'Kigali|Volcanoes National Park',
  ET: 'Addis Ababa|Lalibela',
  NG: 'Lagos|Abuja',
  GH: 'Accra|Cape Coast',
  SN: 'Dakar',
  CI: 'Abidjan',
  ZW: 'Victoria Falls|Harare|Hwange',
  BW: 'Gaborone|Okavango Delta|Okavango|Chobe',
  NA: 'Windhoek|Sossusvlei|Swakopmund',
  MZ: 'Maputo',
  MG: 'Antananarivo',
  MU: 'Port Louis',
  ZM: 'Lusaka|Livingstone',

  US: 'New York|New York City|NYC|Manhattan|Brooklyn|Los Angeles|San Francisco|Chicago|Miami|Orlando|Walt Disney World|Las Vegas|Seattle|Boston|Washington DC|Denver|Dallas|Houston|Austin|Atlanta|San Diego|Philadelphia|New Orleans|Nashville|Honolulu|Hawaii|Maui|Oahu|Kauai|Alaska|Anchorage|Charlotte|Detroit|Minneapolis|Salt Lake City|Grand Canyon|Yellowstone|Yosemite|Napa Valley|Palm Springs|Savannah|Charleston|Aspen|JFK Airport|LaGuardia|Newark Liberty',
  CA: 'Toronto|Vancouver|Montreal|Montréal|Calgary|Ottawa|Quebec City|Quebec|Banff|Whistler|Jasper|Halifax|Yukon',
  MX: 'Mexico City|Cancun|Cancún|Tulum|Playa del Carmen|Los Cabos|Cabo San Lucas|Puerto Vallarta|Oaxaca|Guadalajara|Merida|Riviera Maya|Cozumel',
  CU: 'Havana|Varadero',
  DO: 'Punta Cana|Santo Domingo',
  PR: 'San Juan',
  JM: 'Montego Bay|Kingston|Negril|Ocho Rios',
  BS: 'Nassau|Exuma',
  BB: 'Bridgetown',
  BR: 'Rio de Janeiro|Sao Paulo|São Paulo|Brasilia|Brasília|Iguazu Falls|Amazon rainforest|Florianopolis',
  AR: 'Buenos Aires|Patagonia|Mendoza|Bariloche|Ushuaia',
  CL: 'Santiago|Atacama|Torres del Paine|Valparaiso',
  PE: 'Lima|Cusco|Cuzco|Machu Picchu|Sacred Valley',
  CO: 'Bogota|Bogotá|Cartagena|Medellin|Medellín',
  EC: 'Quito|Galapagos|Galápagos|Guayaquil',
  BO: 'La Paz|Uyuni',
  UY: 'Montevideo|Punta del Este',
  PY: 'Asuncion|Asunción',
  VE: 'Caracas',
  CR: 'San Jose Costa Rica|Guanacaste|Monteverde|Tamarindo',
  PA: 'Panama City|Bocas del Toro',
  GT: 'Guatemala City|Antigua Guatemala|Lake Atitlan',
  BZ: 'Belize City|Ambergris Caye',

  AU: 'Sydney|Melbourne|Brisbane|Perth|Adelaide|Gold Coast|Cairns|Tasmania|Hobart|Darwin|Uluru|Great Barrier Reef|Byron Bay|Kangaroo Island',
  NZ: 'Auckland|Wellington|Christchurch|Queenstown|Rotorua|Milford Sound|Hobbiton',
  FJ: 'Nadi|Suva',
  PF: 'Papeete|Bora Bora|Tahiti|Moorea',
  NC: 'Noumea|Nouméa',
  PG: 'Port Moresby',
  WS: 'Apia',
  TO: 'Nukualofa',
  SB: 'Honiara',
  VU: 'Port Vila',
  MP: 'Saipan',
};

// Terms that are also ordinary English words, place names elsewhere, or brand
// names. They only count when the source text has them capitalized.
export const AMBIGUOUS_TERMS = new Set([
  'turkey', 'chad', 'jordan', 'georgia', 'mali', 'niger', 'guinea', 'grenada',
  'dominica', 'nice', 'split', 'cork', 'male', 'darwin', 'quebec', 'jersey',
  'reunion', 'congo', 'holland', 'english', 'american', 'america', 'china',
  'phoenix', 'santiago', 'delhi', 'kingston', 'bath', 'palma', 'salvador',
  'union', 'sandy', 'colombo',
]);

// Region words that carry no single country.
export const REGION_TERMS = {
  EUROPE: 'Europe|European|Schengen|Balkans|Scandinavia|Nordics|Nordic countries|Mediterranean|Iberian Peninsula|Baltics|Alps',
  ASIA: 'Asia|Asian|Southeast Asia|South East Asia|South Asia|Central Asia|East Asia|Indochina|Himalayas',
  AMERICAS: 'Americas|Latin America|South America|Central America|North America|Caribbean|Patagonia region|Andes',
  AFRICA: 'Africa|African|Sub-Saharan Africa|North Africa|East Africa|West Africa|Southern Africa|Sahara|Maghreb|Sahel',
  'MIDDLE EAST': 'Middle East|Middle Eastern|Gulf states|Persian Gulf|Arabian Peninsula|Levant|GCC',
  OCEANIA: 'Oceania|South Pacific|Polynesia|Melanesia|Australasia',
};

// Two-letter uppercase tokens that read as ISO codes but almost never are.
export const CODE_STOPLIST = new Set([
  'AI', 'AM', 'AS', 'AT', 'BE', 'BY', 'DO', 'ID', 'IE', 'IN', 'IS', 'IT', 'LA',
  'ME', 'MY', 'NO', 'ON', 'OR', 'PA', 'SO', 'TO', 'PM', 'RE', 'SH', 'TV', 'CD',
  'MD', 'MS', 'PR',
]);

export const COUNTRY_NAMES = Object.freeze(
  Object.fromEntries(Object.entries(COUNTRY_TERMS).map(([code, terms]) => [code, terms.split('|')[0]])),
);
